### PR TITLE
Cleanup cmake deps

### PR DESCRIPTION
**Pull request by serge-sans-paille**
At least this works on my setup...

### CODE REVIEW

**Comment by jmmartinez** [comment]
It fails on the docker VM.
I get:

```
/usr/bin/ld: /easy-jit/_build/bin/libEasyJitRuntime.so: undefined reference to symbol '_ZN4llvm23EnableABIBreakingChecksE'                    
```

**Comment by serge-sans-paille** [comment]
mmmmh https://reviews.llvm.org/D26841

**Comment by jmmartinez** [comment]
I tried enabling/disabling the breaking checks and I still get the error. I don't get it.

**Comment by serge-sans-paille** [comment]
Obsoleted by #8

**Pull request closed without merging**
